version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: invoice_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - invoice_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: invoice_backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/invoice-dashboard
      - PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    networks:
      - invoice_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: invoice_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - invoice_net

volumes:
  mongo_data:

networks:
  invoice_net: